//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsInformationSystem
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sisEntities : DbContext
    {
        public sisEntities()
            : base("name=sisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TblAddStdntInfo> TblAddStdntInfoes { get; set; }
        public virtual DbSet<TblAddTeacherInfo> TblAddTeacherInfoes { get; set; }
        public virtual DbSet<TblSchedule> TblSchedules { get; set; }
        public virtual DbSet<TblStdntInfo> TblStdntInfoes { get; set; }
        public virtual DbSet<TblStdntSchoolDetail> TblStdntSchoolDetails { get; set; }
        public virtual DbSet<TblStdntSubj> TblStdntSubjs { get; set; }
        public virtual DbSet<TblSubjInfo> TblSubjInfoes { get; set; }
        public virtual DbSet<TblTeacherInfo> TblTeacherInfoes { get; set; }
    }
}
