//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("sisModel", "FK__TblAddStd__stdnt__4BAC3F29", "TblStdntInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(StudentsInformationSystem.TblStdntInfo), "TblAddStdntInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentsInformationSystem.TblAddStdntInfo), true)]
[assembly: EdmRelationshipAttribute("sisModel", "FK__TblAddTea__teach__534D60F1", "TblTeacherInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(StudentsInformationSystem.TblTeacherInfo), "TblAddTeacherInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentsInformationSystem.TblAddTeacherInfo), true)]
[assembly: EdmRelationshipAttribute("sisModel", "FK__TblSubjIn__sched__59063A47", "TblSchedule", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(StudentsInformationSystem.TblSchedule), "TblSubjInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentsInformationSystem.TblSubjInfo), true)]
[assembly: EdmRelationshipAttribute("sisModel", "FK__TblStdntS__stdnt__4E88ABD4", "TblStdntInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(StudentsInformationSystem.TblStdntInfo), "TblStdntSchoolDetails", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentsInformationSystem.TblStdntSchoolDetail), true)]
[assembly: EdmRelationshipAttribute("sisModel", "FK__TblStdntS__stdnt__5BE2A6F2", "TblStdntInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(StudentsInformationSystem.TblStdntInfo), "TblStdntSubj", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentsInformationSystem.TblStdntSubj), true)]
[assembly: EdmRelationshipAttribute("sisModel", "FK__TblStdntS__offer__5CD6CB2B", "TblSubjInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(StudentsInformationSystem.TblSubjInfo), "TblStdntSubj", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentsInformationSystem.TblStdntSubj), true)]
[assembly: EdmRelationshipAttribute("sisModel", "FK__TblSubjIn__teach__5812160E", "TblTeacherInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(StudentsInformationSystem.TblTeacherInfo), "TblSubjInfo", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(StudentsInformationSystem.TblSubjInfo), true)]

#endregion

namespace StudentsInformationSystem
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class sisEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new sisEntities object using the connection string found in the 'sisEntities' section of the application configuration file.
        /// </summary>
        public sisEntities() : base("name=sisEntities", "sisEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new sisEntities object.
        /// </summary>
        public sisEntities(string connectionString) : base(connectionString, "sisEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new sisEntities object.
        /// </summary>
        public sisEntities(EntityConnection connection) : base(connection, "sisEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TblAddStdntInfo> TblAddStdntInfoes
        {
            get
            {
                if ((_TblAddStdntInfoes == null))
                {
                    _TblAddStdntInfoes = base.CreateObjectSet<TblAddStdntInfo>("TblAddStdntInfoes");
                }
                return _TblAddStdntInfoes;
            }
        }
        private ObjectSet<TblAddStdntInfo> _TblAddStdntInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TblAddTeacherInfo> TblAddTeacherInfoes
        {
            get
            {
                if ((_TblAddTeacherInfoes == null))
                {
                    _TblAddTeacherInfoes = base.CreateObjectSet<TblAddTeacherInfo>("TblAddTeacherInfoes");
                }
                return _TblAddTeacherInfoes;
            }
        }
        private ObjectSet<TblAddTeacherInfo> _TblAddTeacherInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TblSchedule> TblSchedules
        {
            get
            {
                if ((_TblSchedules == null))
                {
                    _TblSchedules = base.CreateObjectSet<TblSchedule>("TblSchedules");
                }
                return _TblSchedules;
            }
        }
        private ObjectSet<TblSchedule> _TblSchedules;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TblStdntInfo> TblStdntInfoes
        {
            get
            {
                if ((_TblStdntInfoes == null))
                {
                    _TblStdntInfoes = base.CreateObjectSet<TblStdntInfo>("TblStdntInfoes");
                }
                return _TblStdntInfoes;
            }
        }
        private ObjectSet<TblStdntInfo> _TblStdntInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TblStdntSchoolDetail> TblStdntSchoolDetails
        {
            get
            {
                if ((_TblStdntSchoolDetails == null))
                {
                    _TblStdntSchoolDetails = base.CreateObjectSet<TblStdntSchoolDetail>("TblStdntSchoolDetails");
                }
                return _TblStdntSchoolDetails;
            }
        }
        private ObjectSet<TblStdntSchoolDetail> _TblStdntSchoolDetails;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TblStdntSubj> TblStdntSubjs
        {
            get
            {
                if ((_TblStdntSubjs == null))
                {
                    _TblStdntSubjs = base.CreateObjectSet<TblStdntSubj>("TblStdntSubjs");
                }
                return _TblStdntSubjs;
            }
        }
        private ObjectSet<TblStdntSubj> _TblStdntSubjs;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TblSubjInfo> TblSubjInfoes
        {
            get
            {
                if ((_TblSubjInfoes == null))
                {
                    _TblSubjInfoes = base.CreateObjectSet<TblSubjInfo>("TblSubjInfoes");
                }
                return _TblSubjInfoes;
            }
        }
        private ObjectSet<TblSubjInfo> _TblSubjInfoes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<TblTeacherInfo> TblTeacherInfoes
        {
            get
            {
                if ((_TblTeacherInfoes == null))
                {
                    _TblTeacherInfoes = base.CreateObjectSet<TblTeacherInfo>("TblTeacherInfoes");
                }
                return _TblTeacherInfoes;
            }
        }
        private ObjectSet<TblTeacherInfo> _TblTeacherInfoes;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TblAddStdntInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTblAddStdntInfoes(TblAddStdntInfo tblAddStdntInfo)
        {
            base.AddObject("TblAddStdntInfoes", tblAddStdntInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TblAddTeacherInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTblAddTeacherInfoes(TblAddTeacherInfo tblAddTeacherInfo)
        {
            base.AddObject("TblAddTeacherInfoes", tblAddTeacherInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TblSchedules EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTblSchedules(TblSchedule tblSchedule)
        {
            base.AddObject("TblSchedules", tblSchedule);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TblStdntInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTblStdntInfoes(TblStdntInfo tblStdntInfo)
        {
            base.AddObject("TblStdntInfoes", tblStdntInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TblStdntSchoolDetails EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTblStdntSchoolDetails(TblStdntSchoolDetail tblStdntSchoolDetail)
        {
            base.AddObject("TblStdntSchoolDetails", tblStdntSchoolDetail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TblStdntSubjs EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTblStdntSubjs(TblStdntSubj tblStdntSubj)
        {
            base.AddObject("TblStdntSubjs", tblStdntSubj);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TblSubjInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTblSubjInfoes(TblSubjInfo tblSubjInfo)
        {
            base.AddObject("TblSubjInfoes", tblSubjInfo);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the TblTeacherInfoes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTblTeacherInfoes(TblTeacherInfo tblTeacherInfo)
        {
            base.AddObject("TblTeacherInfoes", tblTeacherInfo);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sisModel", Name="TblAddStdntInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblAddStdntInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TblAddStdntInfo object.
        /// </summary>
        /// <param name="add_info_record">Initial value of the add_info_record property.</param>
        public static TblAddStdntInfo CreateTblAddStdntInfo(global::System.Int32 add_info_record)
        {
            TblAddStdntInfo tblAddStdntInfo = new TblAddStdntInfo();
            tblAddStdntInfo.add_info_record = add_info_record;
            return tblAddStdntInfo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 add_info_record
        {
            get
            {
                return _add_info_record;
            }
            set
            {
                if (_add_info_record != value)
                {
                    Onadd_info_recordChanging(value);
                    ReportPropertyChanging("add_info_record");
                    _add_info_record = StructuralObject.SetValidValue(value, "add_info_record");
                    ReportPropertyChanged("add_info_record");
                    Onadd_info_recordChanged();
                }
            }
        }
        private global::System.Int32 _add_info_record;
        partial void Onadd_info_recordChanging(global::System.Int32 value);
        partial void Onadd_info_recordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> stdnt_id
        {
            get
            {
                return _stdnt_id;
            }
            set
            {
                Onstdnt_idChanging(value);
                ReportPropertyChanging("stdnt_id");
                _stdnt_id = StructuralObject.SetValidValue(value, "stdnt_id");
                ReportPropertyChanged("stdnt_id");
                Onstdnt_idChanged();
            }
        }
        private Nullable<global::System.Int32> _stdnt_id;
        partial void Onstdnt_idChanging(Nullable<global::System.Int32> value);
        partial void Onstdnt_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String stdnt_address
        {
            get
            {
                return _stdnt_address;
            }
            set
            {
                Onstdnt_addressChanging(value);
                ReportPropertyChanging("stdnt_address");
                _stdnt_address = StructuralObject.SetValidValue(value, true, "stdnt_address");
                ReportPropertyChanged("stdnt_address");
                Onstdnt_addressChanged();
            }
        }
        private global::System.String _stdnt_address;
        partial void Onstdnt_addressChanging(global::System.String value);
        partial void Onstdnt_addressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contact_info
        {
            get
            {
                return _contact_info;
            }
            set
            {
                Oncontact_infoChanging(value);
                ReportPropertyChanging("contact_info");
                _contact_info = StructuralObject.SetValidValue(value, true, "contact_info");
                ReportPropertyChanged("contact_info");
                Oncontact_infoChanged();
            }
        }
        private global::System.String _contact_info;
        partial void Oncontact_infoChanging(global::System.String value);
        partial void Oncontact_infoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sisModel", "FK__TblAddStd__stdnt__4BAC3F29", "TblStdntInfo")]
        public TblStdntInfo TblStdntInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblStdntInfo>("sisModel.FK__TblAddStd__stdnt__4BAC3F29", "TblStdntInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblStdntInfo>("sisModel.FK__TblAddStd__stdnt__4BAC3F29", "TblStdntInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblStdntInfo> TblStdntInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblStdntInfo>("sisModel.FK__TblAddStd__stdnt__4BAC3F29", "TblStdntInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblStdntInfo>("sisModel.FK__TblAddStd__stdnt__4BAC3F29", "TblStdntInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sisModel", Name="TblAddTeacherInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblAddTeacherInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TblAddTeacherInfo object.
        /// </summary>
        /// <param name="add_info_record">Initial value of the add_info_record property.</param>
        public static TblAddTeacherInfo CreateTblAddTeacherInfo(global::System.Int32 add_info_record)
        {
            TblAddTeacherInfo tblAddTeacherInfo = new TblAddTeacherInfo();
            tblAddTeacherInfo.add_info_record = add_info_record;
            return tblAddTeacherInfo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 add_info_record
        {
            get
            {
                return _add_info_record;
            }
            set
            {
                if (_add_info_record != value)
                {
                    Onadd_info_recordChanging(value);
                    ReportPropertyChanging("add_info_record");
                    _add_info_record = StructuralObject.SetValidValue(value, "add_info_record");
                    ReportPropertyChanged("add_info_record");
                    Onadd_info_recordChanged();
                }
            }
        }
        private global::System.Int32 _add_info_record;
        partial void Onadd_info_recordChanging(global::System.Int32 value);
        partial void Onadd_info_recordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> teacher_id
        {
            get
            {
                return _teacher_id;
            }
            set
            {
                Onteacher_idChanging(value);
                ReportPropertyChanging("teacher_id");
                _teacher_id = StructuralObject.SetValidValue(value, "teacher_id");
                ReportPropertyChanged("teacher_id");
                Onteacher_idChanged();
            }
        }
        private Nullable<global::System.Int32> _teacher_id;
        partial void Onteacher_idChanging(Nullable<global::System.Int32> value);
        partial void Onteacher_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String teacher_address
        {
            get
            {
                return _teacher_address;
            }
            set
            {
                Onteacher_addressChanging(value);
                ReportPropertyChanging("teacher_address");
                _teacher_address = StructuralObject.SetValidValue(value, true, "teacher_address");
                ReportPropertyChanged("teacher_address");
                Onteacher_addressChanged();
            }
        }
        private global::System.String _teacher_address;
        partial void Onteacher_addressChanging(global::System.String value);
        partial void Onteacher_addressChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String contact_info
        {
            get
            {
                return _contact_info;
            }
            set
            {
                Oncontact_infoChanging(value);
                ReportPropertyChanging("contact_info");
                _contact_info = StructuralObject.SetValidValue(value, true, "contact_info");
                ReportPropertyChanged("contact_info");
                Oncontact_infoChanged();
            }
        }
        private global::System.String _contact_info;
        partial void Oncontact_infoChanging(global::System.String value);
        partial void Oncontact_infoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true, "email");
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sisModel", "FK__TblAddTea__teach__534D60F1", "TblTeacherInfo")]
        public TblTeacherInfo TblTeacherInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblTeacherInfo>("sisModel.FK__TblAddTea__teach__534D60F1", "TblTeacherInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblTeacherInfo>("sisModel.FK__TblAddTea__teach__534D60F1", "TblTeacherInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblTeacherInfo> TblTeacherInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblTeacherInfo>("sisModel.FK__TblAddTea__teach__534D60F1", "TblTeacherInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblTeacherInfo>("sisModel.FK__TblAddTea__teach__534D60F1", "TblTeacherInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sisModel", Name="TblSchedule")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblSchedule : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TblSchedule object.
        /// </summary>
        /// <param name="schedule_id">Initial value of the schedule_id property.</param>
        public static TblSchedule CreateTblSchedule(global::System.Int32 schedule_id)
        {
            TblSchedule tblSchedule = new TblSchedule();
            tblSchedule.schedule_id = schedule_id;
            return tblSchedule;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 schedule_id
        {
            get
            {
                return _schedule_id;
            }
            set
            {
                if (_schedule_id != value)
                {
                    Onschedule_idChanging(value);
                    ReportPropertyChanging("schedule_id");
                    _schedule_id = StructuralObject.SetValidValue(value, "schedule_id");
                    ReportPropertyChanged("schedule_id");
                    Onschedule_idChanged();
                }
            }
        }
        private global::System.Int32 _schedule_id;
        partial void Onschedule_idChanging(global::System.Int32 value);
        partial void Onschedule_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> room
        {
            get
            {
                return _room;
            }
            set
            {
                OnroomChanging(value);
                ReportPropertyChanging("room");
                _room = StructuralObject.SetValidValue(value, "room");
                ReportPropertyChanged("room");
                OnroomChanged();
            }
        }
        private Nullable<global::System.Int32> _room;
        partial void OnroomChanging(Nullable<global::System.Int32> value);
        partial void OnroomChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String class_day
        {
            get
            {
                return _class_day;
            }
            set
            {
                Onclass_dayChanging(value);
                ReportPropertyChanging("class_day");
                _class_day = StructuralObject.SetValidValue(value, true, "class_day");
                ReportPropertyChanged("class_day");
                Onclass_dayChanged();
            }
        }
        private global::System.String _class_day;
        partial void Onclass_dayChanging(global::System.String value);
        partial void Onclass_dayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String class_hour
        {
            get
            {
                return _class_hour;
            }
            set
            {
                Onclass_hourChanging(value);
                ReportPropertyChanging("class_hour");
                _class_hour = StructuralObject.SetValidValue(value, true, "class_hour");
                ReportPropertyChanged("class_hour");
                Onclass_hourChanged();
            }
        }
        private global::System.String _class_hour;
        partial void Onclass_hourChanging(global::System.String value);
        partial void Onclass_hourChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sisModel", "FK__TblSubjIn__sched__59063A47", "TblSubjInfo")]
        public EntityCollection<TblSubjInfo> TblSubjInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblSubjInfo>("sisModel.FK__TblSubjIn__sched__59063A47", "TblSubjInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblSubjInfo>("sisModel.FK__TblSubjIn__sched__59063A47", "TblSubjInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sisModel", Name="TblStdntInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblStdntInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TblStdntInfo object.
        /// </summary>
        /// <param name="stdnt_id">Initial value of the stdnt_id property.</param>
        public static TblStdntInfo CreateTblStdntInfo(global::System.Int32 stdnt_id)
        {
            TblStdntInfo tblStdntInfo = new TblStdntInfo();
            tblStdntInfo.stdnt_id = stdnt_id;
            return tblStdntInfo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 stdnt_id
        {
            get
            {
                return _stdnt_id;
            }
            set
            {
                if (_stdnt_id != value)
                {
                    Onstdnt_idChanging(value);
                    ReportPropertyChanging("stdnt_id");
                    _stdnt_id = StructuralObject.SetValidValue(value, "stdnt_id");
                    ReportPropertyChanged("stdnt_id");
                    Onstdnt_idChanged();
                }
            }
        }
        private global::System.Int32 _stdnt_id;
        partial void Onstdnt_idChanging(global::System.Int32 value);
        partial void Onstdnt_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String f_name
        {
            get
            {
                return _f_name;
            }
            set
            {
                Onf_nameChanging(value);
                ReportPropertyChanging("f_name");
                _f_name = StructuralObject.SetValidValue(value, true, "f_name");
                ReportPropertyChanged("f_name");
                Onf_nameChanged();
            }
        }
        private global::System.String _f_name;
        partial void Onf_nameChanging(global::System.String value);
        partial void Onf_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String m_name
        {
            get
            {
                return _m_name;
            }
            set
            {
                Onm_nameChanging(value);
                ReportPropertyChanging("m_name");
                _m_name = StructuralObject.SetValidValue(value, true, "m_name");
                ReportPropertyChanged("m_name");
                Onm_nameChanged();
            }
        }
        private global::System.String _m_name;
        partial void Onm_nameChanging(global::System.String value);
        partial void Onm_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String l_ame
        {
            get
            {
                return _l_ame;
            }
            set
            {
                Onl_ameChanging(value);
                ReportPropertyChanging("l_ame");
                _l_ame = StructuralObject.SetValidValue(value, true, "l_ame");
                ReportPropertyChanged("l_ame");
                Onl_ameChanged();
            }
        }
        private global::System.String _l_ame;
        partial void Onl_ameChanging(global::System.String value);
        partial void Onl_ameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> birth_date
        {
            get
            {
                return _birth_date;
            }
            set
            {
                Onbirth_dateChanging(value);
                ReportPropertyChanging("birth_date");
                _birth_date = StructuralObject.SetValidValue(value, "birth_date");
                ReportPropertyChanged("birth_date");
                Onbirth_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _birth_date;
        partial void Onbirth_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onbirth_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value, true, "gender");
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.String _gender;
        partial void OngenderChanging(global::System.String value);
        partial void OngenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String civil_stat
        {
            get
            {
                return _civil_stat;
            }
            set
            {
                Oncivil_statChanging(value);
                ReportPropertyChanging("civil_stat");
                _civil_stat = StructuralObject.SetValidValue(value, true, "civil_stat");
                ReportPropertyChanged("civil_stat");
                Oncivil_statChanged();
            }
        }
        private global::System.String _civil_stat;
        partial void Oncivil_statChanging(global::System.String value);
        partial void Oncivil_statChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sisModel", "FK__TblAddStd__stdnt__4BAC3F29", "TblAddStdntInfo")]
        public EntityCollection<TblAddStdntInfo> TblAddStdntInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblAddStdntInfo>("sisModel.FK__TblAddStd__stdnt__4BAC3F29", "TblAddStdntInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblAddStdntInfo>("sisModel.FK__TblAddStd__stdnt__4BAC3F29", "TblAddStdntInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sisModel", "FK__TblStdntS__stdnt__4E88ABD4", "TblStdntSchoolDetails")]
        public EntityCollection<TblStdntSchoolDetail> TblStdntSchoolDetails
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblStdntSchoolDetail>("sisModel.FK__TblStdntS__stdnt__4E88ABD4", "TblStdntSchoolDetails");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblStdntSchoolDetail>("sisModel.FK__TblStdntS__stdnt__4E88ABD4", "TblStdntSchoolDetails", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sisModel", "FK__TblStdntS__stdnt__5BE2A6F2", "TblStdntSubj")]
        public EntityCollection<TblStdntSubj> TblStdntSubjs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblStdntSubj>("sisModel.FK__TblStdntS__stdnt__5BE2A6F2", "TblStdntSubj");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblStdntSubj>("sisModel.FK__TblStdntS__stdnt__5BE2A6F2", "TblStdntSubj", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sisModel", Name="TblStdntSchoolDetail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblStdntSchoolDetail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TblStdntSchoolDetail object.
        /// </summary>
        /// <param name="school_detail_record">Initial value of the school_detail_record property.</param>
        public static TblStdntSchoolDetail CreateTblStdntSchoolDetail(global::System.Int32 school_detail_record)
        {
            TblStdntSchoolDetail tblStdntSchoolDetail = new TblStdntSchoolDetail();
            tblStdntSchoolDetail.school_detail_record = school_detail_record;
            return tblStdntSchoolDetail;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 school_detail_record
        {
            get
            {
                return _school_detail_record;
            }
            set
            {
                if (_school_detail_record != value)
                {
                    Onschool_detail_recordChanging(value);
                    ReportPropertyChanging("school_detail_record");
                    _school_detail_record = StructuralObject.SetValidValue(value, "school_detail_record");
                    ReportPropertyChanged("school_detail_record");
                    Onschool_detail_recordChanged();
                }
            }
        }
        private global::System.Int32 _school_detail_record;
        partial void Onschool_detail_recordChanging(global::System.Int32 value);
        partial void Onschool_detail_recordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> stdnt_id
        {
            get
            {
                return _stdnt_id;
            }
            set
            {
                Onstdnt_idChanging(value);
                ReportPropertyChanging("stdnt_id");
                _stdnt_id = StructuralObject.SetValidValue(value, "stdnt_id");
                ReportPropertyChanged("stdnt_id");
                Onstdnt_idChanged();
            }
        }
        private Nullable<global::System.Int32> _stdnt_id;
        partial void Onstdnt_idChanging(Nullable<global::System.Int32> value);
        partial void Onstdnt_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String course
        {
            get
            {
                return _course;
            }
            set
            {
                OncourseChanging(value);
                ReportPropertyChanging("course");
                _course = StructuralObject.SetValidValue(value, true, "course");
                ReportPropertyChanged("course");
                OncourseChanged();
            }
        }
        private global::System.String _course;
        partial void OncourseChanging(global::System.String value);
        partial void OncourseChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String department
        {
            get
            {
                return _department;
            }
            set
            {
                OndepartmentChanging(value);
                ReportPropertyChanging("department");
                _department = StructuralObject.SetValidValue(value, true, "department");
                ReportPropertyChanged("department");
                OndepartmentChanged();
            }
        }
        private global::System.String _department;
        partial void OndepartmentChanging(global::System.String value);
        partial void OndepartmentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String yr_lvl
        {
            get
            {
                return _yr_lvl;
            }
            set
            {
                Onyr_lvlChanging(value);
                ReportPropertyChanging("yr_lvl");
                _yr_lvl = StructuralObject.SetValidValue(value, true, "yr_lvl");
                ReportPropertyChanged("yr_lvl");
                Onyr_lvlChanged();
            }
        }
        private global::System.String _yr_lvl;
        partial void Onyr_lvlChanging(global::System.String value);
        partial void Onyr_lvlChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sisModel", "FK__TblStdntS__stdnt__4E88ABD4", "TblStdntInfo")]
        public TblStdntInfo TblStdntInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblStdntInfo>("sisModel.FK__TblStdntS__stdnt__4E88ABD4", "TblStdntInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblStdntInfo>("sisModel.FK__TblStdntS__stdnt__4E88ABD4", "TblStdntInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblStdntInfo> TblStdntInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblStdntInfo>("sisModel.FK__TblStdntS__stdnt__4E88ABD4", "TblStdntInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblStdntInfo>("sisModel.FK__TblStdntS__stdnt__4E88ABD4", "TblStdntInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sisModel", Name="TblStdntSubj")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblStdntSubj : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TblStdntSubj object.
        /// </summary>
        /// <param name="stdnt_subj_record">Initial value of the stdnt_subj_record property.</param>
        public static TblStdntSubj CreateTblStdntSubj(global::System.Int32 stdnt_subj_record)
        {
            TblStdntSubj tblStdntSubj = new TblStdntSubj();
            tblStdntSubj.stdnt_subj_record = stdnt_subj_record;
            return tblStdntSubj;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 stdnt_subj_record
        {
            get
            {
                return _stdnt_subj_record;
            }
            set
            {
                if (_stdnt_subj_record != value)
                {
                    Onstdnt_subj_recordChanging(value);
                    ReportPropertyChanging("stdnt_subj_record");
                    _stdnt_subj_record = StructuralObject.SetValidValue(value, "stdnt_subj_record");
                    ReportPropertyChanged("stdnt_subj_record");
                    Onstdnt_subj_recordChanged();
                }
            }
        }
        private global::System.Int32 _stdnt_subj_record;
        partial void Onstdnt_subj_recordChanging(global::System.Int32 value);
        partial void Onstdnt_subj_recordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> stdnt_id
        {
            get
            {
                return _stdnt_id;
            }
            set
            {
                Onstdnt_idChanging(value);
                ReportPropertyChanging("stdnt_id");
                _stdnt_id = StructuralObject.SetValidValue(value, "stdnt_id");
                ReportPropertyChanged("stdnt_id");
                Onstdnt_idChanged();
            }
        }
        private Nullable<global::System.Int32> _stdnt_id;
        partial void Onstdnt_idChanging(Nullable<global::System.Int32> value);
        partial void Onstdnt_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String offercode
        {
            get
            {
                return _offercode;
            }
            set
            {
                OnoffercodeChanging(value);
                ReportPropertyChanging("offercode");
                _offercode = StructuralObject.SetValidValue(value, true, "offercode");
                ReportPropertyChanged("offercode");
                OnoffercodeChanged();
            }
        }
        private global::System.String _offercode;
        partial void OnoffercodeChanging(global::System.String value);
        partial void OnoffercodeChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sisModel", "FK__TblStdntS__stdnt__5BE2A6F2", "TblStdntInfo")]
        public TblStdntInfo TblStdntInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblStdntInfo>("sisModel.FK__TblStdntS__stdnt__5BE2A6F2", "TblStdntInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblStdntInfo>("sisModel.FK__TblStdntS__stdnt__5BE2A6F2", "TblStdntInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblStdntInfo> TblStdntInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblStdntInfo>("sisModel.FK__TblStdntS__stdnt__5BE2A6F2", "TblStdntInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblStdntInfo>("sisModel.FK__TblStdntS__stdnt__5BE2A6F2", "TblStdntInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sisModel", "FK__TblStdntS__offer__5CD6CB2B", "TblSubjInfo")]
        public TblSubjInfo TblSubjInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblSubjInfo>("sisModel.FK__TblStdntS__offer__5CD6CB2B", "TblSubjInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblSubjInfo>("sisModel.FK__TblStdntS__offer__5CD6CB2B", "TblSubjInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblSubjInfo> TblSubjInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblSubjInfo>("sisModel.FK__TblStdntS__offer__5CD6CB2B", "TblSubjInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblSubjInfo>("sisModel.FK__TblStdntS__offer__5CD6CB2B", "TblSubjInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sisModel", Name="TblSubjInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblSubjInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TblSubjInfo object.
        /// </summary>
        /// <param name="offercode">Initial value of the offercode property.</param>
        public static TblSubjInfo CreateTblSubjInfo(global::System.String offercode)
        {
            TblSubjInfo tblSubjInfo = new TblSubjInfo();
            tblSubjInfo.offercode = offercode;
            return tblSubjInfo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String offercode
        {
            get
            {
                return _offercode;
            }
            set
            {
                if (_offercode != value)
                {
                    OnoffercodeChanging(value);
                    ReportPropertyChanging("offercode");
                    _offercode = StructuralObject.SetValidValue(value, false, "offercode");
                    ReportPropertyChanged("offercode");
                    OnoffercodeChanged();
                }
            }
        }
        private global::System.String _offercode;
        partial void OnoffercodeChanging(global::System.String value);
        partial void OnoffercodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String subj_name
        {
            get
            {
                return _subj_name;
            }
            set
            {
                Onsubj_nameChanging(value);
                ReportPropertyChanging("subj_name");
                _subj_name = StructuralObject.SetValidValue(value, true, "subj_name");
                ReportPropertyChanged("subj_name");
                Onsubj_nameChanged();
            }
        }
        private global::System.String _subj_name;
        partial void Onsubj_nameChanging(global::System.String value);
        partial void Onsubj_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> teacher_id
        {
            get
            {
                return _teacher_id;
            }
            set
            {
                Onteacher_idChanging(value);
                ReportPropertyChanging("teacher_id");
                _teacher_id = StructuralObject.SetValidValue(value, "teacher_id");
                ReportPropertyChanged("teacher_id");
                Onteacher_idChanged();
            }
        }
        private Nullable<global::System.Int32> _teacher_id;
        partial void Onteacher_idChanging(Nullable<global::System.Int32> value);
        partial void Onteacher_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> schedule
        {
            get
            {
                return _schedule;
            }
            set
            {
                OnscheduleChanging(value);
                ReportPropertyChanging("schedule");
                _schedule = StructuralObject.SetValidValue(value, "schedule");
                ReportPropertyChanged("schedule");
                OnscheduleChanged();
            }
        }
        private Nullable<global::System.Int32> _schedule;
        partial void OnscheduleChanging(Nullable<global::System.Int32> value);
        partial void OnscheduleChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sisModel", "FK__TblSubjIn__sched__59063A47", "TblSchedule")]
        public TblSchedule TblSchedule
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblSchedule>("sisModel.FK__TblSubjIn__sched__59063A47", "TblSchedule").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblSchedule>("sisModel.FK__TblSubjIn__sched__59063A47", "TblSchedule").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblSchedule> TblScheduleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblSchedule>("sisModel.FK__TblSubjIn__sched__59063A47", "TblSchedule");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblSchedule>("sisModel.FK__TblSubjIn__sched__59063A47", "TblSchedule", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sisModel", "FK__TblStdntS__offer__5CD6CB2B", "TblStdntSubj")]
        public EntityCollection<TblStdntSubj> TblStdntSubjs
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblStdntSubj>("sisModel.FK__TblStdntS__offer__5CD6CB2B", "TblStdntSubj");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblStdntSubj>("sisModel.FK__TblStdntS__offer__5CD6CB2B", "TblStdntSubj", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sisModel", "FK__TblSubjIn__teach__5812160E", "TblTeacherInfo")]
        public TblTeacherInfo TblTeacherInfo
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblTeacherInfo>("sisModel.FK__TblSubjIn__teach__5812160E", "TblTeacherInfo").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblTeacherInfo>("sisModel.FK__TblSubjIn__teach__5812160E", "TblTeacherInfo").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<TblTeacherInfo> TblTeacherInfoReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<TblTeacherInfo>("sisModel.FK__TblSubjIn__teach__5812160E", "TblTeacherInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<TblTeacherInfo>("sisModel.FK__TblSubjIn__teach__5812160E", "TblTeacherInfo", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="sisModel", Name="TblTeacherInfo")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class TblTeacherInfo : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new TblTeacherInfo object.
        /// </summary>
        /// <param name="teacher_id">Initial value of the teacher_id property.</param>
        public static TblTeacherInfo CreateTblTeacherInfo(global::System.Int32 teacher_id)
        {
            TblTeacherInfo tblTeacherInfo = new TblTeacherInfo();
            tblTeacherInfo.teacher_id = teacher_id;
            return tblTeacherInfo;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 teacher_id
        {
            get
            {
                return _teacher_id;
            }
            set
            {
                if (_teacher_id != value)
                {
                    Onteacher_idChanging(value);
                    ReportPropertyChanging("teacher_id");
                    _teacher_id = StructuralObject.SetValidValue(value, "teacher_id");
                    ReportPropertyChanged("teacher_id");
                    Onteacher_idChanged();
                }
            }
        }
        private global::System.Int32 _teacher_id;
        partial void Onteacher_idChanging(global::System.Int32 value);
        partial void Onteacher_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String f_name
        {
            get
            {
                return _f_name;
            }
            set
            {
                Onf_nameChanging(value);
                ReportPropertyChanging("f_name");
                _f_name = StructuralObject.SetValidValue(value, true, "f_name");
                ReportPropertyChanged("f_name");
                Onf_nameChanged();
            }
        }
        private global::System.String _f_name;
        partial void Onf_nameChanging(global::System.String value);
        partial void Onf_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String m_name
        {
            get
            {
                return _m_name;
            }
            set
            {
                Onm_nameChanging(value);
                ReportPropertyChanging("m_name");
                _m_name = StructuralObject.SetValidValue(value, true, "m_name");
                ReportPropertyChanged("m_name");
                Onm_nameChanged();
            }
        }
        private global::System.String _m_name;
        partial void Onm_nameChanging(global::System.String value);
        partial void Onm_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String l_ame
        {
            get
            {
                return _l_ame;
            }
            set
            {
                Onl_ameChanging(value);
                ReportPropertyChanging("l_ame");
                _l_ame = StructuralObject.SetValidValue(value, true, "l_ame");
                ReportPropertyChanged("l_ame");
                Onl_ameChanged();
            }
        }
        private global::System.String _l_ame;
        partial void Onl_ameChanging(global::System.String value);
        partial void Onl_ameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> birth_date
        {
            get
            {
                return _birth_date;
            }
            set
            {
                Onbirth_dateChanging(value);
                ReportPropertyChanging("birth_date");
                _birth_date = StructuralObject.SetValidValue(value, "birth_date");
                ReportPropertyChanged("birth_date");
                Onbirth_dateChanged();
            }
        }
        private Nullable<global::System.DateTime> _birth_date;
        partial void Onbirth_dateChanging(Nullable<global::System.DateTime> value);
        partial void Onbirth_dateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String gender
        {
            get
            {
                return _gender;
            }
            set
            {
                OngenderChanging(value);
                ReportPropertyChanging("gender");
                _gender = StructuralObject.SetValidValue(value, true, "gender");
                ReportPropertyChanged("gender");
                OngenderChanged();
            }
        }
        private global::System.String _gender;
        partial void OngenderChanging(global::System.String value);
        partial void OngenderChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String civil_stat
        {
            get
            {
                return _civil_stat;
            }
            set
            {
                Oncivil_statChanging(value);
                ReportPropertyChanging("civil_stat");
                _civil_stat = StructuralObject.SetValidValue(value, true, "civil_stat");
                ReportPropertyChanged("civil_stat");
                Oncivil_statChanged();
            }
        }
        private global::System.String _civil_stat;
        partial void Oncivil_statChanging(global::System.String value);
        partial void Oncivil_statChanged();

        #endregion

        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sisModel", "FK__TblAddTea__teach__534D60F1", "TblAddTeacherInfo")]
        public EntityCollection<TblAddTeacherInfo> TblAddTeacherInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblAddTeacherInfo>("sisModel.FK__TblAddTea__teach__534D60F1", "TblAddTeacherInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblAddTeacherInfo>("sisModel.FK__TblAddTea__teach__534D60F1", "TblAddTeacherInfo", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("sisModel", "FK__TblSubjIn__teach__5812160E", "TblSubjInfo")]
        public EntityCollection<TblSubjInfo> TblSubjInfoes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<TblSubjInfo>("sisModel.FK__TblSubjIn__teach__5812160E", "TblSubjInfo");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<TblSubjInfo>("sisModel.FK__TblSubjIn__teach__5812160E", "TblSubjInfo", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
