//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentsInformationSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblTeacherInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblTeacherInfo()
        {
            this.TblAddTeacherInfoes = new HashSet<TblAddTeacherInfo>();
            this.TblSubjInfoes = new HashSet<TblSubjInfo>();
        }
    
        public int teacher_id { get; set; }
        public string f_name { get; set; }
        public string m_name { get; set; }
        public string l_ame { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string gender { get; set; }
        public string civil_stat { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblAddTeacherInfo> TblAddTeacherInfoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TblSubjInfo> TblSubjInfoes { get; set; }
    }
}
